Add tests for a Book functionality
RomanMenzheres/BookStore pull request #14
Opened 2024-01-07 20:53 UTC by RomanMenzheres

Created tests for book and category services and  controllers

2024-01-08 19:42 UTC, olekskov requested changes

2024-01-08 19:42 UTC, olekskov commented on src/test/java/com/example/bookstore/controller/CategoryControllerTest.java
> +        assertEquals(expected, Arrays.stream(actual).toList());
Cannot say it's mandatory but your code formatting looks very strange for me
Please try following approach, maybe you also find it better
```suggestion
        List<CategoryDto> expected = new ArrayList<>();
        expected.add(new CategoryDto(1L, "Fantasy", "Fantasy books"));
        expected.add(new CategoryDto(2L, "Historical fiction", "Historical books"));
        expected.add(new CategoryDto(3L, "Mystery", "Mystery books"));

        MvcResult result = mockMvc
                .perform(get("/api/categories").contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andReturn();

        CategoryDto[] actual = objectMapper.readValue(
                result.getResponse().getContentAsByteArray(), CategoryDto[].class);

        assertEquals(expected.size(), actual.length);
        assertEquals(expected, Arrays.stream(actual).toList());
```

2024-01-08 19:42 UTC, olekskov commented on src/test/java/com/example/bookstore/service/BookServiceTest.java
> +            """)
Why to waste 2 additional lines with text block?
```suggestion
    @DisplayName("Verify save() method works")
```

2024-01-08 19:42 UTC, olekskov commented on src/test/java/com/example/bookstore/service/BookServiceTest.java
> +        expected.setCoverImage(book.getCoverImage());
Please extract creation of objects to separate methods, it takes 80% of whole test

2024-01-09 15:19 UTC, okuzan approved these changes

2024-01-09 20:11 UTC, merged