Add ability to search books task
RomanMenzheres/BookStore pull request #4
Opened 2023-12-17 17:22 UTC by RomanMenzheres

Added ability to search books.

2023-12-18 12:28 UTC, okuzan requested changes

2023-12-18 12:28 UTC, okuzan commented on src/main/java/com/example/bookstore/controller/BookController.java
> +
```suggestion
```

2023-12-18 12:28 UTC, okuzan commented on src/main/java/com/example/bookstore/searching/book/BookSpecificationBuilder.java
> +                    .getSpecificationProvider("title")
let's make author and title constants

2023-12-19 10:28 UTC, kozhukhovsky approved these changes

2023-12-19 16:49 UTC, merged